apiVersion: v1
kind: Namespace
metadata:
  name: ghcs

---

apiVersion: v1
kind: Service
metadata:
  name: ghcs
  namespace: ghcs
spec:
  selector:
    app: ghcs
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
  name: ghcs
  namespace: ghcs
spec:
  rules:
  - host: ghcs.cb-eks.kearos.net
    http:
      paths:
      - path: /
        backend:
          serviceName: ghcs
          servicePort: 80